#!/usr/bin/env sh

#ddev-generated
## Description: Run redis-cli inside the DragonflyDB container
## Usage: redis-cli [flags] [args]
## Example: "ddev redis-cli KEYS *" or "ddev redis-cli INFO" or "ddev redis-cli --version"

redis-cli -p 6379 -h "${DRAGONFLY_HOSTNAME:-dragonfly}" $@
