name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test (${{ matrix.test }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [generic, drupal10, drupal11]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install DDEV
        run: curl -fsSL https://ddev.com/install.sh | bash

      - name: Run tests
        run: bash tests/test.sh ${{ matrix.test }}
