name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Debug with tmate"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test (DDEV ${{ matrix.ddev_version }}, ${{ matrix.bats_tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
        bats_tag: [generic, drupal10, drupal11]
      fail-fast: false
    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          test_command: bats tests --filter-tags ${{ matrix.bats_tag }}
